Vagrant.configure("2") do |config|
    config.vm.box = "Aptly-CI/macOS-10.14" # Один з доступних MacOS образів
  
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      brew install --cask dotnet-sdk
      echo '<?xml version="1.0" encoding="utf-8"?>
      <configuration>
        <packageSources>
          <add key="MyBaGetRepo" value="http://localhost:5000/v3/index.json" />
        </packageSources>
      </configuration>' > ~/.nuget/NuGet/NuGet.Config
      dotnet tool install --global --add-source http://localhost:5000/v3/index.json lab-work-4-sy --version 1.0.0
    SHELL
  end
  